name: CleanArchitectureRxSwift
options:
  bundleIdPrefix: com.clean
targets:
  Domain:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Domain]
    dependencies:
      - carthage: RxSwift
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.0"
    sources:
      - path: DomainTests
    dependencies:
      - carthage: RxTest
      - carthage: RxBlocking
      - target: Domain
  NetworkPlatform:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    sources: [NetworkPlatform]
    dependencies:
      - target: Domain
      - carthage: RxSwift
      - carthage: RxAlamofire
      - carthage: Alamofire
      - carthage: RxAtomic
  RealmPlatform:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    sources: [RealmPlatform]
    dependencies:
      - target: Domain
      - carthage: RxSwift
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: RxRealm  
  CleanArchitectureRxSwift:
      type: application
      platform: iOS
      deploymentTarget: "12.0"
      sources: [CleanArchitectureRxSwift]
      dependencies:
        - target: Domain
        - target: NetworkPlatform
        - target: RealmPlatform
        - carthage: RxSwift
        - carthage: RxCocoa  